services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    depends_on:
      - db
    volumes:
      - pgadmin:/var/lib/pgadmin

  backend:
    build:
      context: ./backend
    container_name: board-manager-backend
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SERVER_PORT: ${SERVER_PORT}
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'

  frontend:
    build:
      context: ./frontend
    container_name: board-manager-frontend
    ports:
      - '3000:80'
    depends_on:
      - backend
    environment:
      SERVER_PORT: ${SERVER_PORT}
      HOST_NAME: ${HOST_NAME}
      VITE_SERVER_URL: ${VITE_SERVER_URL}

volumes:
  postgres_data:
  pgadmin:
